# Generated by Django 4.1.6 on 2023-02-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willyou', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeddingImages',
            new_name='WeddingImage',
        ),
    ]
