# Generated by Django 4.1.6 on 2023-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willyou', '0002_rename_weddingimages_weddingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
